export const components = [
  {
    name: "Button",
    icon: "SmartButtonIcon",
    id: "button",
    type: "button",
    children: "button",
    showInPanel: true,
  },
  {
    name: "Input",
    icon: "InputIcon",
    id: "input",
    type: "input",
    showInPanel: true,
  },
  {
    name: "TextField",
    icon: "TextFieldsIcon",
    id: "textarea",
    type: "textarea",
    showInPanel: true,
  },
  {
    name: "Text",
    icon: "TextFormatIcon",
    id: "text",
    type: "text",
    children: "text",
    showInPanel: true,
  },
  {
    name: "Image",
    icon: "ImageIcon",
    id: "image",
    type: "image",
    showInPanel: true,
  },
  {
    name: "Checkbox",
    icon: "CheckBoxIcon",
    id: "checkbox",
    type: "checkbox",
    showInPanel: true,
  },
  {
    name: "Radio",
    icon: "RadioButtonCheckedIcon",
    id: "radio",
    type: "radio",
    showInPanel: true,
  },
  {
    name: "Switch",
    icon: "ToggleOnIcon",
    id: "switch",
    type: "switch",
    showInPanel: true,
  },
  {
    name: "Heading",
    icon: "HMobiledataIcon",
    id: "heading",
    type: "heading",
    children: "Heading Text",
    showInPanel: true,
  },
  {
    name: "Card",
    icon: "CreditCardIcon",
    id: "card",
    type: "card",
    showInPanel: false,
  },
  {
    name: "Link",
    icon: "LinkIcon",
    id: "link",
    type: "link",
    children: "Link",
    showInPanel: true,
  },
  {
    name: "Container",
    description: "A container component like a div, section, or article",
    id: "container",
    type: "container",
    showInPanel: false,
  },
];
